import {
  AirVent,
  Armchair,
  Bed,
  Bike,
  Bus,
  Camera,
  Car,
  ChefHat,
  Coffee,
  CookingPot,
  Dumbbell,
  Fan,
  Headphones,
  Home,
  KeyRound,
  Lamp,
  type LucideIcon,
  Moon,
  Package,
  Refrigerator,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Scissors,
  Sofa,
  Sparkles,
  Trees,
  Utensils,
  WashingMachine,
  Waves,
  Wifi,
  Wrench,
} from "lucide-react";

const RULES: { match: RegExp; icon: LucideIcon }[] = [
  // Building facilities
  { match: /pool|swim/i, icon: Waves },
  { match: /gym|fitness/i, icon: Dumbbell },
  { match: /squash|court|sport/i, icon: Bike },
  { match: /caf[eé]|food court|canteen/i, icon: ChefHat },
  { match: /barber|salon/i, icon: Scissors },
  { match: /mart|convenience|grocer|shop/i, icon: ShoppingBasket },
  { match: /laundry/i, icon: WashingMachine },
  { match: /vending/i, icon: Package },
  { match: /prayer|surau/i, icon: Moon },
  { match: /security|guard|controlled access/i, icon: ShieldCheck },
  { match: /access card|key|entry/i, icon: KeyRound },
  { match: /cctv|camera|monitor/i, icon: Camera },
  { match: /car ?park|parking/i, icon: Car },
  { match: /shuttle|bus|mrt|transport/i, icon: Bus },
  { match: /garden|outdoor|landscape|park/i, icon: Trees },

  // Included in your stay
  { match: /wi-?fi|internet/i, icon: Wifi },
  { match: /clean|housekeep/i, icon: Sparkles },
  { match: /support|warden|help|24\/7/i, icon: Headphones },
  { match: /maintenance|repair|fix/i, icon: Wrench },

  // Inside your apartment
  { match: /furnish/i, icon: Home },
  { match: /bed/i, icon: Bed },
  { match: /desk|study/i, icon: Lamp },
  { match: /wardrobe|closet|clothes/i, icon: Shirt },
  { match: /air ?-?condition|aircond|cooling/i, icon: AirVent },
  { match: /\bfan\b/i, icon: Fan },
  { match: /kitchen|cook/i, icon: CookingPot },
  { match: /fridge|refrigerator/i, icon: Refrigerator },
  { match: /dining/i, icon: Utensils },
  { match: /sofa|living|lounge/i, icon: Sofa },
  { match: /coffee table/i, icon: Coffee },
  { match: /washing machine|washer/i, icon: WashingMachine },
  { match: /chair|seat/i, icon: Armchair },
];

/** Icons an admin can pick from, keyed by a stable name stored in the database. */
export const ICON_CHOICES: Record<string, LucideIcon> = {
  waves: Waves,
  dumbbell: Dumbbell,
  bike: Bike,
  chefHat: ChefHat,
  scissors: Scissors,
  shoppingBasket: ShoppingBasket,
  washingMachine: WashingMachine,
  package: Package,
  moon: Moon,
  shieldCheck: ShieldCheck,
  keyRound: KeyRound,
  camera: Camera,
  car: Car,
  bus: Bus,
  trees: Trees,
  wifi: Wifi,
  sparkles: Sparkles,
  headphones: Headphones,
  wrench: Wrench,
  home: Home,
  bed: Bed,
  lamp: Lamp,
  shirt: Shirt,
  airVent: AirVent,
  fan: Fan,
  cookingPot: CookingPot,
  refrigerator: Refrigerator,
  utensils: Utensils,
  sofa: Sofa,
  coffee: Coffee,
  armchair: Armchair,
  check: Check,
  star: Star,
  heart: Heart,
  droplets: Droplets,
  zap: Zap,
  building: Building2,
  users: Users,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  tv: Tv,
  bath: Bath,
  dog: Dog,
  gamepad: Gamepad2,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  lock: Lock,
  flame: Flame,
  leaf: Leaf,
  sun: Sun,
  umbrella: Umbrella,
  wind: Wind,
  cctv: Cctv,
  elevator: MoveVertical,
  printer: Printer,
  bell: Bell,
  calendar: CalendarDays,
};

export const ICON_LABELS: Record<string, string> = {
  waves: "Pool / water",
  dumbbell: "Gym",
  bike: "Sports",
  chefHat: "Café / food",
  scissors: "Salon",
  shoppingBasket: "Mini mart",
  washingMachine: "Laundry",
  package: "Vending / parcel",
  moon: "Prayer room",
  shieldCheck: "Security",
  keyRound: "Access card",
  camera: "Camera",
  car: "Car park",
  bus: "Shuttle bus",
  trees: "Garden",
  wifi: "Wi-Fi",
  sparkles: "Cleaning",
  headphones: "Support",
  wrench: "Maintenance",
  home: "Home",
  bed: "Bed",
  lamp: "Study desk",
  shirt: "Wardrobe",
  airVent: "Air-conditioning",
  fan: "Fan",
  cookingPot: "Kitchen",
  refrigerator: "Fridge",
  utensils: "Dining",
  sofa: "Sofa / living",
  coffee: "Coffee table",
  armchair: "Chair",
  check: "Tick",
  star: "Star",
  heart: "Heart",
  droplets: "Water heater",
  zap: "Electricity",
  building: "Building",
  users: "Community",
  clock: "Hours",
  mapPin: "Location",
  phone: "Phone",
  tv: "TV",
  bath: "Bathroom",
  dog: "Pets",
  gamepad: "Games room",
  bookOpen: "Study room",
  briefcase: "Co-working",
  lock: "Lockers",
  flame: "Cooker / hob",
  leaf: "Green space",
  sun: "Rooftop",
  umbrella: "Sheltered",
  wind: "Ventilation",
  cctv: "CCTV",
  elevator: "Lift",
  printer: "Printing",
  bell: "Reception",
  calendar: "Events",
};

export type IconOverrides = Record<string, string>;

export function facilityIcon(label: string, overrides?: IconOverrides): LucideIcon {
  const key = overrides?.[label];
  if (key && ICON_CHOICES[key]) return ICON_CHOICES[key]!;
  return RULES.find((r) => r.match.test(label))?.icon ?? Home;
}

