import { createServerFn } from "@tanstack/react-start";

import type { Bed, BedPatch, Unit, UnitRoom } from "@/lib/ops-store";

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Homes: physical inventory (units -> rooms -> beds).
 *
 * The tables mirror the ops-store types one-for-one, so everything here is a
 * name translation: snake_case in Postgres, camelCase in TypeScript. Nothing
 * outside this file sees a database column name.
 */

/**
 * units / rooms / beds / import_batches are not in the generated Database type
 * yet (that file is regenerated by Lovable, so it is not edited by hand).
 * Cast to any until it catches up.
 */
async function admin(): Promise<any> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin as any;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (v?: string) => !!v && UUID.test(v);

/* ---------------- row -> type ---------------- */

function toBed(row: any): Bed {
  return {
    id: row.id,
    label: row.label,
    status: row.status,
    residentId: row.resident_id ?? undefined,
    residentName: row.resident_name ?? undefined,
    studentId: row.student_id ?? undefined,
    university: row.university ?? undefined,
    nationality: row.nationality ?? undefined,
    gender: row.gender ?? undefined,
    tenancyStart: row.tenancy_start ?? undefined,
    tenancyEnd: row.tenancy_end ?? undefined,
    rent: row.rent ?? undefined,
    holdFor: row.hold_for ?? undefined,
    holdUntil: row.hold_until ?? undefined,
    enquiryId: row.enquiry_id ?? undefined,
  };
}

function toRoom(row: any, beds: any[]): UnitRoom {
  return {
    id: row.id,
    letter: row.letter,
    roomTypeCode: row.room_type_code ?? "",
    occupancy: row.occupancy === "twin" || row.occupancy === "unit" ? row.occupancy : "single",
    rent: Number(row.rent ?? 0),
    beds: beds
      .filter((b) => b.room_id === row.id)
      .sort(
        (a, b) =>
          (a.sort_order ?? 0) - (b.sort_order ?? 0) ||
          String(a.label).localeCompare(String(b.label)),
      )
      .map(toBed),
  };
}

function toUnit(row: any, rooms: any[], beds: any[]): Unit {
  const res = row.residences ?? {};
  return {
    id: row.id,
    code: row.code ?? "",
    residenceId: row.residence_id,
    residenceName: res.name ?? "",
    residenceSlug: res.slug ?? "",
    unitNo: row.unit_no ?? "",
    block: row.block ?? "",
    floor: row.floor ?? "",
    unitType: row.unit_type ?? "",
    gender: row.gender ?? "",
    wholeUnit: !!row.whole_unit,
    wholeUnitRent: Number(row.whole_unit_rent ?? 0),
    notes: row.notes ?? "",
    rooms: rooms
      .filter((r) => r.unit_id === row.id)
      .sort(
        (a, b) =>
          (a.sort_order ?? 0) - (b.sort_order ?? 0) ||
          String(a.letter).localeCompare(String(b.letter)),
      )
      .map((r) => toRoom(r, beds)),
  };
}

/* ---------------- read ---------------- */

export const listUnits = createServerFn({ method: "GET" }).handler(async (): Promise<Unit[]> => {
  const supabase = await admin();
  const { data: units, error } = await supabase
    .from("units")
    .select("*, residences(name, slug)")
    .order("code");
  if (error) throw new Error(error.message);
  if (!units?.length) return [];

  const unitIds = units.map((u: any) => u.id);
  const { data: rooms, error: roomErr } = await supabase
    .from("rooms")
    .select("*")
    .in("unit_id", unitIds);
  if (roomErr) throw new Error(roomErr.message);

  const roomIds = (rooms ?? []).map((r: any) => r.id);
  const beds = roomIds.length
    ? ((await supabase.from("beds").select("*").in("room_id", roomIds)).data ?? [])
    : [];

  return units.map((u: any) => toUnit(u, rooms ?? [], beds));
});

/* ---------------- write ---------------- */

/**
 * Upsert a whole unit with its rooms and beds.
 *
 * Rooms match on (unit_id, letter) and beds on (room_id, label), so saving an
 * existing unit keeps every id stable and preserves bed status. Anything the
 * payload no longer contains is removed.
 */
export const saveUnitRow = createServerFn({ method: "POST" })
  .inputValidator((data: { unit: Unit; importBatchId?: string }) => data)
  .handler(async ({ data }): Promise<Unit> => {
    const supabase = await admin();
    const { unit, importBatchId } = data;

    const unitRow = {
      residence_id: unit.residenceId,
      code: unit.code,
      unit_no: unit.unitNo,
      block: unit.block ?? "",
      floor: unit.floor ?? "",
      unit_type: unit.unitType ?? "",
      gender: unit.gender ?? "",
      whole_unit: !!unit.wholeUnit,
      whole_unit_rent: unit.wholeUnitRent ?? 0,
      notes: unit.notes ?? "",
      ...(importBatchId ? { import_batch_id: importBatchId } : {}),
    };

    const { data: saved, error } = await supabase
      .from("units")
      .upsert(isUuid(unit.id) ? { id: unit.id, ...unitRow } : unitRow, {
        onConflict: "residence_id,unit_no",
      })
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    const unitId = (saved as any).id as string;

    // rooms
    const roomRows = unit.rooms.map((r, i) => ({
      unit_id: unitId,
      letter: r.letter,
      room_type_code: r.roomTypeCode ?? "",
      occupancy: r.occupancy,
      rent: r.rent ?? 0,
      sort_order: i,
      ...(importBatchId ? { import_batch_id: importBatchId } : {}),
    }));
    const { data: savedRooms, error: roomErr } = roomRows.length
      ? await supabase
          .from("rooms")
          .upsert(roomRows, { onConflict: "unit_id,letter" })
          .select("id, letter")
      : { data: [] as any[], error: null };
    if (roomErr) throw new Error(roomErr.message);

    const keptLetters = unit.rooms.map((r) => r.letter);
    let dropRooms = supabase.from("rooms").delete().eq("unit_id", unitId);
    if (keptLetters.length) dropRooms = dropRooms.not("letter", "in", `(${keptLetters.join(",")})`);
    await dropRooms;

    // beds
    const roomIdByLetter = new Map<string, string>(
      (savedRooms ?? []).map((r: any) => [r.letter as string, r.id as string]),
    );
    const bedRows: any[] = [];
    for (const room of unit.rooms) {
      const roomId = roomIdByLetter.get(room.letter);
      if (!roomId) continue;
      room.beds.forEach((b, i) => {
        bedRows.push({
          room_id: roomId,
          label: b.label,
          status: b.status ?? "vacant",
          hold_for: b.holdFor ?? null,
          hold_until: b.holdUntil ?? null,
          enquiry_id: isUuid(b.enquiryId) ? b.enquiryId : null,
          resident_id: b.residentId ?? null,
          resident_name: b.residentName ?? null,
          student_id: b.studentId ?? null,
          university: b.university ?? null,
          nationality: b.nationality ?? null,
          gender: b.gender ?? null,
          tenancy_start: b.tenancyStart || null,
          tenancy_end: b.tenancyEnd || null,
          rent: b.rent ?? null,
          sort_order: i,
          ...(importBatchId ? { import_batch_id: importBatchId } : {}),
        });
      });
    }
    if (bedRows.length) {
      const { error: bedErr } = await supabase
        .from("beds")
        .upsert(bedRows, { onConflict: "room_id,label" });
      if (bedErr) throw new Error(bedErr.message);
    }

    for (const room of unit.rooms) {
      const roomId = roomIdByLetter.get(room.letter);
      if (!roomId) continue;
      const labels = room.beds.map((b) => b.label);
      let dropBeds = supabase.from("beds").delete().eq("room_id", roomId);
      if (labels.length)
        dropBeds = dropBeds.not("label", "in", `(${labels.map((l) => `"${l}"`).join(",")})`);
      await dropBeds;
    }

    return await readUnit(supabase, unitId);
  });

async function readUnit(supabase: any, unitId: string): Promise<Unit> {
  const { data: row, error } = await supabase
    .from("units")
    .select("*, residences(name, slug)")
    .eq("id", unitId)
    .single();
  if (error) throw new Error(error.message);
  const { data: rooms } = await supabase.from("rooms").select("*").eq("unit_id", unitId);
  const roomIds = (rooms ?? []).map((r: any) => r.id);
  const beds = roomIds.length
    ? ((await supabase.from("beds").select("*").in("room_id", roomIds)).data ?? [])
    : [];
  return toUnit(row, rooms ?? [], beds);
}

export const deleteUnitRow = createServerFn({ method: "POST" })
  .inputValidator((data: { id: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.id)) return { ok: true };
    const supabase = await admin();
    const { error } = await supabase.from("units").delete().eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

export const updateBedRow = createServerFn({ method: "POST" })
  .inputValidator((data: { bedId: string; patch: BedPatch }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.bedId)) return { ok: true };
    const supabase = await admin();
    const p = data.patch;
    const row: Record<string, unknown> = {};

    if ("label" in p) row["label"] = p.label;
    if ("status" in p) row["status"] = p.status ?? "vacant";
    if ("holdFor" in p) row["hold_for"] = p.holdFor ?? null;
    if ("holdUntil" in p) row["hold_until"] = p.holdUntil ?? null;
    if ("enquiryId" in p) row["enquiry_id"] = isUuid(p.enquiryId) ? p.enquiryId : null;
    if ("residentId" in p) row["resident_id"] = p.residentId ?? null;
    if ("residentName" in p) row["resident_name"] = p.residentName ?? null;
    if ("studentId" in p) row["student_id"] = p.studentId ?? null;
    if ("university" in p) row["university"] = p.university ?? null;
    if ("nationality" in p) row["nationality"] = p.nationality ?? null;
    if ("gender" in p) row["gender"] = p.gender ?? null;
    if ("tenancyStart" in p) row["tenancy_start"] = p.tenancyStart || null;
    if ("tenancyEnd" in p) row["tenancy_end"] = p.tenancyEnd || null;
    if ("rent" in p) row["rent"] = p.rent ?? null;
    if (!Object.keys(row).length) return { ok: true };

    const { error } = await supabase
      .from("beds")
      .update(row as any)
      .eq("id", data.bedId);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/* ---------------- import batches ---------------- */

export const createImportBatch = createServerFn({ method: "POST" })
  .inputValidator((data: { kind: string; filename?: string; rowCount?: number }) => data)
  .handler(async ({ data }) => {
    const supabase = await admin();
    const { data: row, error } = await supabase
      .from("import_batches")
      .insert({
        kind: data.kind,
        filename: data.filename ?? "",
        row_count: data.rowCount ?? 0,
      } as any)
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    return { id: (row as any).id as string };
  });
