import { createServerFn } from "@tanstack/react-start";

import type { Bed, BedPatch, Unit, UnitRoom, UpcomingStay } from "@/lib/ops-store";

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Homes: physical inventory (units -> rooms -> beds).
 *
 * The tables mirror the ops-store types one-for-one, so everything here is a
 * name translation: snake_case in Postgres, camelCase in TypeScript. Nothing
 * outside this file sees a database column name.
 */

/**
 * units / rooms / beds / import_batches are not in the generated Database type
 * yet (that file is regenerated by Lovable, so it is not edited by hand).
 * Cast to any until it catches up.
 */
async function admin(): Promise<any> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin as any;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (v?: string) => !!v && UUID.test(v);

/* ---------------- row -> type ---------------- */

function toBed(row: any): Bed {
  return {
    id: row.id,
    label: row.label,
    status: row.status,
    residentId: row.resident_id ?? undefined,
    residentName: row.resident_name ?? undefined,
    studentId: row.student_id ?? undefined,
    university: row.university ?? undefined,
    nationality: row.nationality ?? undefined,
    gender: row.gender ?? undefined,
    tenancyStart: row.tenancy_start ?? undefined,
    tenancyEnd: row.tenancy_end ?? undefined,
    rent: row.rent ?? undefined,
    holdFor: row.hold_for ?? undefined,
    holdUntil: row.hold_until ?? undefined,
    enquiryId: row.enquiry_id ?? undefined,
    upcoming: row.upcoming?.length ? row.upcoming : undefined,
  };
}

/**
 * The stays to come on each bed while somebody else is its resident (9 Oct
 * 2026). Nothing on the bed row stores them - they are read from where each
 * one lives:
 *   Reserved   an unpaid hold on the bed (beds.enquiry_id), when the bed's
 *              resident is somebody else
 *   Booked     a paid tenancy placed on the bed (tenancies.bed_id) whose
 *              resident is not the bed's, has not ended, and is not living
 *              in another bed already
 * Earliest first, so a bed can have more than one.
 */
async function attachUpcoming(supabase: any, beds: any[]) {
  if (!beds.length) return beds;
  const bedIds = new Set(beds.map((b) => String(b.id)));
  const { klToday } = await import("@/lib/kl-date");
  const today = klToday();
  // every placed stay not over yet - one read, rather than a list of hundreds of bed ids in the address
  const { data: tens } = await supabase
    .from("tenancies")
    .select("resident_id, enquiry_id, bed_id, start_date, end_date")
    .not("bed_id", "is", null)
    .or(`end_date.is.null,end_date.gte.${today}`);
  const tenancies = ((tens ?? []) as any[]).filter((t) => bedIds.has(String(t.bed_id)));
  const holdIds = beds.filter((b) => b.enquiry_id && b.resident_id).map((b) => b.enquiry_id);
  const enquiryIds = [...new Set([...holdIds, ...tenancies.map((t) => t.enquiry_id).filter(Boolean)])] as string[];
  const residentIds = [...new Set(tenancies.map((t) => t.resident_id).filter(Boolean))] as string[];
  const [{ data: enquiries }, { data: residents }, { data: invoices }, { data: living }] = await Promise.all([
    enquiryIds.length
      ? supabase.from("enquiries").select("id, reference, full_name, gender, university, move_in, move_out, monthly_rent, resident_id").in("id", enquiryIds)
      : { data: [] },
    residentIds.length
      ? supabase.from("residents").select("id, full_name, gender, university, status, resident_code, quickbooks_id, enquiry_id").in("id", residentIds)
      : { data: [] },
    enquiryIds.length
      ? supabase.from("invoices").select("enquiry_id, monthly_rent, created_at").in("enquiry_id", enquiryIds).neq("status", "void").order("created_at", { ascending: false })
      : { data: [] },
    residentIds.length
      ? supabase.from("beds").select("resident_id").in("resident_id", residentIds).in("status", ["active", "notice"])
      : { data: [] },
  ]);
  const enq = new Map(((enquiries ?? []) as any[]).map((e) => [e.id, e]));
  const res = new Map(((residents ?? []) as any[]).map((r) => [r.id, r]));
  const rentOf = (id?: string) => Number(((invoices ?? []) as any[]).find((i) => i.enquiry_id === id)?.monthly_rent || enq.get(id ?? "")?.monthly_rent || 0) || undefined;
  const livingIn = new Set(((living ?? []) as any[]).map((b) => b.resident_id));

  return beds.map((b) => {
    const list: UpcomingStay[] = [];
    // an unpaid hold on a bed somebody else is the resident of
    const e = b.enquiry_id && b.resident_id ? enq.get(b.enquiry_id) : undefined;
    if (e && e.resident_id !== b.resident_id) {
      list.push({
        enquiryId: e.id,
        reference: e.reference || undefined,
        name: String(e.full_name ?? ""),
        gender: e.gender || undefined,
        university: e.university || undefined,
        start: e.move_in || undefined,
        end: e.move_out || undefined,
        rent: rentOf(e.id),
        status: "reserved",
      });
    }
    for (const t of tenancies) {
      if (t.bed_id !== b.id || t.resident_id === b.resident_id || livingIn.has(t.resident_id)) continue;
      const r = res.get(t.resident_id);
      if (!r || String(r.status ?? "").toLowerCase() === "inactive") continue;
      const te = enq.get(t.enquiry_id ?? "");
      list.push({
        enquiryId: t.enquiry_id || undefined,
        reference: te?.reference || undefined,
        residentId: r.id,
        name: String(r.full_name || te?.full_name || ""),
        code: String(r.resident_code || r.quickbooks_id || "") || undefined,
        gender: r.gender || undefined,
        university: r.university || te?.university || undefined,
        start: t.start_date || undefined,
        end: t.end_date || undefined,
        rent: rentOf(t.enquiry_id),
        status: "booked",
      });
    }
    list.sort((x, y) => String(x.start ?? "").localeCompare(String(y.start ?? "")));
    return list.length ? { ...b, upcoming: list } : b;
  });
}

function toRoom(row: any, beds: any[]): UnitRoom {
  return {
    id: row.id,
    letter: row.letter,
    roomTypeCode: row.room_type_code ?? "",
    occupancy: row.occupancy === "twin" || row.occupancy === "unit" ? row.occupancy : "single",
    rent: Number(row.rent ?? 0),
    beds: beds
      .filter((b) => b.room_id === row.id)
      .sort(
        (a, b) =>
          (a.sort_order ?? 0) - (b.sort_order ?? 0) ||
          String(a.label).localeCompare(String(b.label)),
      )
      .map(toBed),
  };
}

function toUnit(row: any, rooms: any[], beds: any[]): Unit {
  const res = row.residences ?? {};
  return {
    id: row.id,
    code: row.code ?? "",
    residenceId: row.residence_id,
    residenceName: res.name ?? "",
    residenceSlug: res.slug ?? "",
    unitNo: row.unit_no ?? "",
    block: row.block ?? "",
    floor: row.floor ?? "",
    unitType: row.unit_type ?? "",
    gender: row.gender ?? "",
    wholeUnit: !!row.whole_unit,
    wholeUnitRent: Number(row.whole_unit_rent ?? 0),
    notes: row.notes ?? "",
    deactivatedAt: row.deactivated_at ?? "",
    deactivationReason: row.deactivation_reason ?? "",
    rooms: rooms
      .filter((r) => r.unit_id === row.id)
      .sort(
        (a, b) =>
          (a.sort_order ?? 0) - (b.sort_order ?? 0) ||
          String(a.letter).localeCompare(String(b.letter)),
      )
      .map((r) => toRoom(r, beds)),
  };
}

/* ---------------- read ---------------- */

export const listUnits = createServerFn({ method: "GET" }).handler(async (): Promise<Unit[]> => {
  const supabase = await admin();
  const { data: units, error } = await supabase
    .from("units")
    .select("*, residences(name, slug)")
    .order("code");
  if (error) throw new Error(error.message);
  if (!units?.length) return [];

  const unitIds = units.map((u: any) => u.id);
  const { data: rooms, error: roomErr } = await supabase
    .from("rooms")
    .select("*")
    .in("unit_id", unitIds);
  if (roomErr) throw new Error(roomErr.message);

  const roomIds = (rooms ?? []).map((r: any) => r.id);
  const beds = roomIds.length
    ? await attachUpcoming(supabase, (await supabase.from("beds").select("*").in("room_id", roomIds)).data ?? [])
    : [];

  return units.map((u: any) => toUnit(u, rooms ?? [], beds));
});

/* ---------------- write ---------------- */

/**
 * Upsert a whole unit with its rooms and beds.
 *
 * Rooms match on (unit_id, letter) and beds on (room_id, label), so saving an
 * existing unit keeps every id stable and preserves bed status. Anything the
 * payload no longer contains is removed.
 */
export const saveUnitRow = createServerFn({ method: "POST" })
  .inputValidator((data: { unit: Unit; importBatchId?: string }) => data)
  .handler(async ({ data }): Promise<Unit> => {
    const supabase = await admin();
    const { unit, importBatchId } = data;

    // a unit is let whole (one "Unit" bed) or by room - never both. Every screen
    // keeps to this, and this refuses anything that did not
    const slots = unit.rooms.filter((r) => r.letter.toLowerCase() === "unit");
    if (slots.length && slots.length !== unit.rooms.length) {
      throw new Error(`${unit.unitNo}: a unit is let either whole or by room, not both`);
    }

    /*
     * The code this unit is known by - U001, U002, and no dash, the way the
     * master list writes it.
     *
     * ONE sequence across every residence, not one per residence. The Arc ends
     * at U075 and Solstice carries straight on at U076, so the next new unit of
     * either is U087. Per-residence letters were tidier to read, but these
     * codes are already printed on invoices that have gone out, and an invoice
     * quoting U063 has to lead back to a unit called U063.
     *
     * Worked out here rather than in the page, because only here is the
     * residence certain: Add unit mints a draft before anybody has picked one,
     * and the bulk upload has no say in it at all.
     *
     * A unit that already exists keeps the code it has. Codes are read by
     * people and printed on lists, so one must never move under a unit that is
     * merely being edited.
     *
     * A new one takes the HIGHEST number already given rather than how many
     * units there are. U028 is a deliberate gap - B-13A-01 is deactivated - and
     * counting would hand that number out a second time.
     */
    const found = isUuid(unit.id)
      ? await supabase.from("units").select("code").eq("id", unit.id).maybeSingle()
      : await supabase
          .from("units")
          .select("code")
          .eq("residence_id", unit.residenceId)
          .eq("unit_no", unit.unitNo)
          .maybeSingle();

    let code = String((found.data as any)?.code ?? "").trim();
    if (!code) {
      const { data: res } = await supabase
        .from("residences")
        .select("unit_prefix")
        .eq("id", unit.residenceId)
        .maybeSingle();
      /*
       * Blank means U. It used to fall back to the first letter of the
       * residence's name, which made sense while each had its own letter and
       * is simply wrong now - it would mint T001 for The Arc.
       */
      const prefix = String((res as any)?.unit_prefix ?? "").trim() || "U";
      // every unit, not this residence's: the sequence is shared, and counting
      // within one residence would hand Solstice a number The Arc already has
      const { data: all } = await supabase.from("units").select("code");
      const highest = ((all ?? []) as any[]).reduce((max, r) => {
        const digits = /(\d+)\s*$/.exec(String(r.code ?? ""));
        return digits ? Math.max(max, Number(digits[1])) : max;
      }, 0);
      code = `${prefix}${String(highest + 1).padStart(3, "0")}`;
    }

    const unitRow = {
      residence_id: unit.residenceId,
      code,
      unit_no: unit.unitNo,
      block: unit.block ?? "",
      floor: unit.floor ?? "",
      unit_type: unit.unitType ?? "",
      gender: unit.gender ?? "",
      // whether it is let whole follows from its rooms, so the two cannot disagree
      whole_unit: slots.length > 0,
      whole_unit_rent: unit.wholeUnitRent ?? 0,
      notes: unit.notes ?? "",
      ...(importBatchId ? { import_batch_id: importBatchId } : {}),
    };

    const { data: saved, error } = await supabase
      .from("units")
      .upsert(isUuid(unit.id) ? { id: unit.id, ...unitRow } : unitRow, {
        onConflict: "residence_id,unit_no",
      })
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    const unitId = (saved as any).id as string;

    // rooms
    const roomRows = unit.rooms.map((r, i) => ({
      unit_id: unitId,
      letter: r.letter,
      room_type_code: r.roomTypeCode ?? "",
      occupancy: r.occupancy,
      rent: r.rent ?? 0,
      sort_order: i,
      ...(importBatchId ? { import_batch_id: importBatchId } : {}),
    }));
    const { data: savedRooms, error: roomErr } = roomRows.length
      ? await supabase
          .from("rooms")
          .upsert(roomRows, { onConflict: "unit_id,letter" })
          .select("id, letter")
      : { data: [] as any[], error: null };
    if (roomErr) throw new Error(roomErr.message);

    const keptLetters = unit.rooms.map((r) => r.letter);
    let dropRooms = supabase.from("rooms").delete().eq("unit_id", unitId);
    if (keptLetters.length) dropRooms = dropRooms.not("letter", "in", `(${keptLetters.join(",")})`);
    await dropRooms;

    // beds
    const roomIdByLetter = new Map<string, string>(
      (savedRooms ?? []).map((r: any) => [r.letter as string, r.id as string]),
    );
    const bedRows: any[] = [];
    for (const room of unit.rooms) {
      const roomId = roomIdByLetter.get(room.letter);
      if (!roomId) continue;
      room.beds.forEach((b, i) => {
        bedRows.push({
          room_id: roomId,
          label: b.label,
          status: b.status ?? "vacant",
          hold_for: b.holdFor ?? null,
          hold_until: b.holdUntil ?? null,
          enquiry_id: isUuid(b.enquiryId) ? b.enquiryId : null,
          resident_id: b.residentId ?? null,
          resident_name: b.residentName ?? null,
          student_id: b.studentId ?? null,
          university: b.university ?? null,
          nationality: b.nationality ?? null,
          gender: b.gender ?? null,
          tenancy_start: b.tenancyStart || null,
          tenancy_end: b.tenancyEnd || null,
          rent: b.rent ?? null,
          sort_order: i,
          ...(importBatchId ? { import_batch_id: importBatchId } : {}),
        });
      });
    }
    if (bedRows.length) {
      const { error: bedErr } = await supabase
        .from("beds")
        .upsert(bedRows, { onConflict: "room_id,label" });
      if (bedErr) throw new Error(bedErr.message);
    }

    for (const room of unit.rooms) {
      const roomId = roomIdByLetter.get(room.letter);
      if (!roomId) continue;
      const labels = room.beds.map((b) => b.label);
      let dropBeds = supabase.from("beds").delete().eq("room_id", roomId);
      if (labels.length)
        dropBeds = dropBeds.not("label", "in", `(${labels.map((l) => `"${l}"`).join(",")})`);
      await dropBeds;
    }

    return await readUnit(supabase, unitId);
  });

async function readUnit(supabase: any, unitId: string): Promise<Unit> {
  const { data: row, error } = await supabase
    .from("units")
    .select("*, residences(name, slug)")
    .eq("id", unitId)
    .single();
  if (error) throw new Error(error.message);
  const { data: rooms } = await supabase.from("rooms").select("*").eq("unit_id", unitId);
  const roomIds = (rooms ?? []).map((r: any) => r.id);
  const beds = roomIds.length
    ? await attachUpcoming(supabase, (await supabase.from("beds").select("*").in("room_id", roomIds)).data ?? [])
    : [];
  return toUnit(row, rooms ?? [], beds);
}

/**
 * Take a unit out of service, or put it back.
 *
 * Deliberately NOT part of saveUnitRow: that rewrites the unit's rooms and beds
 * to match what it was handed, which is exactly how the bulk upload detaches
 * residents. Turning a unit off must touch one row and nothing else.
 *
 * A unit with somebody in it is refused. Deactivating hides its beds from
 * placement, so a resident inside one would quietly vanish from Homes - the
 * same rule Release follows: somebody living there is moved, not swept aside.
 */
export const setUnitDeactivated = createServerFn({ method: "POST" })
  .inputValidator((data: { id: string; deactivated: boolean; reason?: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.id)) return { ok: true as const };
    const supabase = await admin();

    /*
     * What it says now. A unit already out of service keeps the date it went
     * out: editing the reason is a correction to the wording, and re-stamping
     * it as today would destroy the one fact this row exists to hold.
     */
    const { data: current } = await supabase
      .from("units")
      .select("deactivated_at")
      .eq("id", data.id)
      .maybeSingle();
    const alreadyOff = Boolean((current as any)?.deactivated_at);

    // only when turning a LIVE unit off - a unit already off is hidden from
    // placement, so nobody can have moved into it since
    if (data.deactivated && !alreadyOff) {
      const { data: rooms } = await supabase.from("rooms").select("id").eq("unit_id", data.id);
      const roomIds = ((rooms ?? []) as any[]).map((r) => r.id);
      if (roomIds.length) {
        const { data: taken } = await supabase
          .from("beds")
          .select("label, resident_name")
          .in("room_id", roomIds)
          .or("resident_id.not.is.null,enquiry_id.not.is.null");
        const who = ((taken ?? []) as any[])
          .map((b) => String(b.resident_name ?? "").trim() || String(b.label ?? ""))
          .filter(Boolean);
        if (who.length) {
          return {
            ok: false as const,
            error: `${who.join(", ")} ${who.length === 1 ? "is" : "are"} still in this unit. Move them out before deactivating it.`,
          };
        }
      }
    }

    const { error } = await supabase
      .from("units")
      .update({
        deactivated_at: data.deactivated
          ? ((current as any)?.deactivated_at ?? new Date().toISOString())
          : null,
        // the reason goes with the deactivation and is cleared when it comes back
        deactivation_reason: data.deactivated ? (data.reason ?? "").trim() : "",
      } as any)
      .eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });

/**
 * Work a booking's stage out again after its bed has moved.
 *
 * Placement writes beds directly - it is inventory, not the booking flow - so
 * nothing here recomputed the stage, and a paid student moved to another bed
 * kept whatever stage the move left behind. Reserving one read "Room reserved"
 * on a booking whose fee was already in.
 *
 * The stage is worked out from what is true of the booking now, so this only
 * has to be asked; it is never told what to say.
 */
export const syncStageForBooking = createServerFn({ method: "POST" })
  .inputValidator((data: { enquiryId: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.enquiryId)) return { ok: true as const };
    const supabase = await admin();
    const { syncBookingStage } = await import("@/lib/booking-lifecycle");
    await syncBookingStage(supabase, data.enquiryId);
    return { ok: true as const };
  });

export const deleteUnitRow = createServerFn({ method: "POST" })
  .inputValidator((data: { id: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.id)) return { ok: true };
    const supabase = await admin();
    const { error } = await supabase.from("units").delete().eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

export const updateBedRow = createServerFn({ method: "POST" })
  .inputValidator((data: { bedId: string; patch: BedPatch }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.bedId)) return { ok: true };
    const supabase = await admin();
    const p = data.patch;
    const row: Record<string, unknown> = {};

    if ("label" in p) row["label"] = p.label;
    if ("status" in p) row["status"] = p.status ?? "vacant";
    if ("holdFor" in p) row["hold_for"] = p.holdFor ?? null;
    if ("holdUntil" in p) row["hold_until"] = p.holdUntil ?? null;
    if ("enquiryId" in p) row["enquiry_id"] = isUuid(p.enquiryId) ? p.enquiryId : null;
    if ("residentId" in p) row["resident_id"] = p.residentId ?? null;
    if ("residentName" in p) row["resident_name"] = p.residentName ?? null;
    if ("studentId" in p) row["student_id"] = p.studentId ?? null;
    if ("university" in p) row["university"] = p.university ?? null;
    if ("nationality" in p) row["nationality"] = p.nationality ?? null;
    if ("gender" in p) row["gender"] = p.gender ?? null;
    if ("tenancyStart" in p) row["tenancy_start"] = p.tenancyStart || null;
    if ("tenancyEnd" in p) row["tenancy_end"] = p.tenancyEnd || null;
    if ("rent" in p) row["rent"] = p.rent ?? null;
    if (!Object.keys(row).length) return { ok: true };

    const { error } = await supabase
      .from("beds")
      .update(row as any)
      .eq("id", data.bedId);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/* ---------------- import batches ---------------- */

export const createImportBatch = createServerFn({ method: "POST" })
  .inputValidator((data: { kind: string; filename?: string; rowCount?: number }) => data)
  .handler(async ({ data }) => {
    const supabase = await admin();
    const { data: row, error } = await supabase
      .from("import_batches")
      .insert({
        kind: data.kind,
        filename: data.filename ?? "",
        row_count: data.rowCount ?? 0,
      } as any)
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    return { id: (row as any).id as string };
  });

/* ---------------- placement: one transaction each, in the database ---------------- */

const notMigrated = (error: { message: string }) =>
  /function .* does not exist|Could not find the function/i.test(error.message);

/** What a placement function says when the database has not had its migration yet. */
function rpcError(error: { message: string }) {
  return notMigrated(error)
    ? "The database needs the placement update (20261009100000_dated_placement.sql) before rooms can be reserved this way."
    : error.message;
}

/**
 * Reserve a bed for a booking or a resident, or move them (9 Oct 2026). Every
 * route that places somebody - the booking's room picker, Homes -> Reserve -
 * comes here. The database checks every date, gender and capacity rule again
 * after locking the units involved, so a second admin taking the same room is
 * refused rather than written over - and success is only said once the write
 * is in.
 */
export const placeStay = createServerFn({ method: "POST" })
  .inputValidator(
    (data: { enquiryId?: string; residentId?: string; bedId: string; whole?: boolean; holdUntil?: string }) => data,
  )
  .handler(async ({ data }) => {
    const enquiryId = isUuid(data.enquiryId) ? data.enquiryId! : null;
    const residentId = isUuid(data.residentId) ? data.residentId! : null;
    if ((!enquiryId && !residentId) || !isUuid(data.bedId)) return { ok: false as const, error: "Choose a room first.", detail: "" };
    const supabase = await admin();
    const { data: res, error } = await supabase.rpc("place_stay", {
      p_enquiry: enquiryId,
      p_resident: residentId,
      p_bed: data.bedId,
      p_whole: !!data.whole,
      p_hold_until: data.holdUntil || null,
    });
    if (error && notMigrated(error) && enquiryId) return holdTheOldWay(supabase, { enquiryId, bedId: data.bedId, ...(data.holdUntil ? { holdUntil: data.holdUntil } : {}) });
    if (error) return { ok: false as const, error: rpcError(error), detail: "" };
    const out = res as { ok: boolean; error?: string; detail?: string; placed?: "now" | "later" };
    if (!out?.ok) return { ok: false as const, error: out?.error || "The room could not be reserved.", detail: out?.detail ?? "" };
    if (enquiryId) {
      const { syncBookingStage } = await import("@/lib/booking-lifecycle");
      await syncBookingStage(supabase, enquiryId);
    }
    return { ok: true as const, placed: out.placed ?? "now" };
  });

/**
 * Before the migration: an empty bed is held the way it always was. A bed
 * somebody is in, or a move, needs the database update - refused, not guessed.
 */
async function holdTheOldWay(supabase: any, data: { enquiryId: string; bedId: string; holdUntil?: string }) {
  const [{ data: bed }, { data: e }] = await Promise.all([
    supabase.from("beds").select("status, resident_id, enquiry_id").eq("id", data.bedId).maybeSingle(),
    supabase.from("enquiries").select("full_name, gender, university, nationality").eq("id", data.enquiryId).maybeSingle(),
  ]);
  const { data: had } = await supabase.from("beds").select("id").eq("enquiry_id", data.enquiryId).limit(1);
  if (!bed || bed.status !== "vacant" || bed.resident_id || bed.enquiry_id || (had ?? []).length) {
    return { ok: false as const, error: rpcError({ message: "function place_stay does not exist" }), detail: "" };
  }
  const { error } = await supabase
    .from("beds")
    .update({
      enquiry_id: data.enquiryId,
      status: "held",
      hold_for: e?.full_name ?? null,
      hold_until: data.holdUntil || null,
      gender: e?.gender || null,
      university: e?.university || null,
      nationality: e?.nationality || null,
    })
    .eq("id", data.bedId)
    .eq("status", "vacant");
  if (error) return { ok: false as const, error: error.message, detail: "" };
  const { syncBookingStage } = await import("@/lib/booking-lifecycle");
  await syncBookingStage(supabase, data.enquiryId);
  return { ok: true as const, placed: "now" as const };
}

/**
 * A checked-out resident leaves their bed: whoever has it next becomes its
 * resident, Booked until they arrive; otherwise it is emptied. Their tenancy
 * keeps the bed, so their statement still says where they lived.
 */
export const releaseAfterCheckout = createServerFn({ method: "POST" })
  .inputValidator((data: { residentId: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.residentId)) return { ok: true as const, promoted: [] as string[] };
    const supabase = await admin();
    const { data: res, error } = await supabase.rpc("release_after_checkout", { p_resident: data.residentId });
    if (error && notMigrated(error)) {
      // before the migration: emptied as it always was - nobody can be booked next yet
      const { error: e2 } = await supabase
        .from("beds")
        .update({
          status: "vacant", resident_id: null, resident_name: null, student_id: null, university: null,
          nationality: null, gender: null, hold_for: null, hold_until: null, enquiry_id: null,
          tenancy_start: null, tenancy_end: null, rent: null,
        })
        .eq("resident_id", data.residentId);
      if (e2) throw new Error(e2.message);
      return { ok: true as const, promoted: [] as string[] };
    }
    if (error) throw new Error(rpcError(error));
    const beds = ((res as any)?.beds ?? []) as { next: string | null }[];
    return { ok: true as const, promoted: beds.map((b) => b.next).filter(Boolean) as string[] };
  });

/** The assigned resident has arrived: their bed goes Booked -> Active. Never by date alone. */
export async function activateAtCheckIn(supabase: any, residentId: string) {
  const { data: res, error } = await supabase.rpc("activate_at_checkin", { p_resident: residentId });
  if (error && notMigrated(error)) {
    // before the migration: the bed they are on goes Active, as it always did
    const { error: e2 } = await supabase
      .from("beds")
      .update({ status: "active", hold_for: null, hold_until: null })
      .eq("resident_id", residentId)
      .in("status", ["held", "booked"]);
    return e2 ? { ok: false as const, error: e2.message } : { ok: true as const };
  }
  if (error) return { ok: false as const, error: rpcError(error) };
  const out = res as { ok: boolean; error?: string };
  return out?.ok ? { ok: true as const } : { ok: false as const, error: out?.error || "Check-in could not be recorded." };
}

export const activateResidentBed = createServerFn({ method: "POST" })
  .inputValidator((data: { residentId: string }) => data)
  .handler(async ({ data }) => {
    if (!isUuid(data.residentId)) return { ok: false as const, error: "Resident not found." };
    return activateAtCheckIn(await admin(), data.residentId);
  });
