/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookViewingRouteImport } from './routes/book-viewing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as AdminWebsiteIndexRouteImport } from './routes/admin.website.index'
import { Route as PropertiesSlugIndexRouteImport } from './routes/properties.$slug.index'
import { Route as AdminWebsiteResidencesIndexRouteImport } from './routes/admin.website.residences.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookViewingRoute = BookViewingRouteImport.update({
  id: '/book-viewing',
  path: '/book-viewing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteIndexRoute = AdminWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const PropertiesSlugIndexRoute = PropertiesSlugIndexRouteImport.update({
  id: '/properties/$slug/',
  path: '/properties/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteResidencesIndexRoute =
  AdminWebsiteResidencesIndexRouteImport.update({
    id: '/residences/',
    path: '/residences/',
    getParentRoute: () => AdminWebsiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/admin/website/residences/': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin': typeof AdminIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/website': typeof AdminWebsiteIndexRoute
  '/properties/$slug': typeof PropertiesSlugIndexRoute
  '/admin/website/residences': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/admin/website/residences/': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book-viewing'
    | '/contact'
    | '/admin/appointments'
    | '/admin/bookings'
    | '/admin/website'
    | '/admin/'
    | '/properties/'
    | '/admin/website/'
    | '/properties/$slug/'
    | '/admin/website/residences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-viewing'
    | '/contact'
    | '/admin/appointments'
    | '/admin/bookings'
    | '/admin'
    | '/properties'
    | '/admin/website'
    | '/properties/$slug'
    | '/admin/website/residences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book-viewing'
    | '/contact'
    | '/admin/appointments'
    | '/admin/bookings'
    | '/admin/website'
    | '/admin/'
    | '/properties/'
    | '/admin/website/'
    | '/properties/$slug/'
    | '/admin/website/residences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookViewingRoute: typeof BookViewingRoute
  ContactRoute: typeof ContactRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  PropertiesSlugIndexRoute: typeof PropertiesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-viewing': {
      id: '/book-viewing'
      path: '/book-viewing'
      fullPath: '/book-viewing'
      preLoaderRoute: typeof BookViewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/': {
      id: '/admin/website/'
      path: '/'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminWebsiteIndexRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/properties/$slug/': {
      id: '/properties/$slug/'
      path: '/properties/$slug'
      fullPath: '/properties/$slug/'
      preLoaderRoute: typeof PropertiesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/residences/': {
      id: '/admin/website/residences/'
      path: '/residences'
      fullPath: '/admin/website/residences/'
      preLoaderRoute: typeof AdminWebsiteResidencesIndexRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
  }
}

interface AdminWebsiteRouteChildren {
  AdminWebsiteIndexRoute: typeof AdminWebsiteIndexRoute
  AdminWebsiteResidencesIndexRoute: typeof AdminWebsiteResidencesIndexRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteIndexRoute: AdminWebsiteIndexRoute,
  AdminWebsiteResidencesIndexRoute: AdminWebsiteResidencesIndexRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookViewingRoute: BookViewingRoute,
  ContactRoute: ContactRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  PropertiesSlugIndexRoute: PropertiesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
