/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminUnlockRouteImport } from './routes/admin-unlock'
import { Route as BookViewingRouteImport } from './routes/book-viewing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminHomesRouteImport } from './routes/admin.homes'
import { Route as AdminResidentsRouteImport } from './routes/admin.residents'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as AdminAppointmentsSettingsRouteImport } from './routes/admin.appointments.settings'
import { Route as AdminHomesIndexRouteImport } from './routes/admin.homes.index'
import { Route as AdminHomesAvailabilityRouteImport } from './routes/admin.homes.availability'
import { Route as AdminHomesUnitsRouteImport } from './routes/admin.homes.units'
import { Route as AdminResidentsIndexRouteImport } from './routes/admin.residents.index'
import { Route as AdminResidentsIdRouteImport } from './routes/admin.residents.$id'
import { Route as AdminResidentsPaymentsRouteImport } from './routes/admin.residents.payments'
import { Route as AdminResidentsTenanciesRouteImport } from './routes/admin.residents.tenancies'
import { Route as AdminWebsiteIndexRouteImport } from './routes/admin.website.index'
import { Route as PropertiesSlugIndexRouteImport } from './routes/properties.$slug.index'
import { Route as AdminWebsiteResidencesIndexRouteImport } from './routes/admin.website.residences.index'
import { Route as AdminWebsiteResidencesIdRouteImport } from './routes/admin.website.residences.$id'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnlockRoute = AdminUnlockRouteImport.update({
  id: '/admin-unlock',
  path: '/admin-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const BookViewingRoute = BookViewingRouteImport.update({
  id: '/book-viewing',
  path: '/book-viewing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomesRoute = AdminHomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppointmentsRoute,
} as any)
const AdminAppointmentsSettingsRoute =
  AdminAppointmentsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAppointmentsRoute,
  } as any)
const AdminHomesIndexRoute = AdminHomesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminHomesRoute,
} as any)
const AdminHomesAvailabilityRoute = AdminHomesAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminHomesRoute,
} as any)
const AdminHomesUnitsRoute = AdminHomesUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminHomesRoute,
} as any)
const AdminResidentsIndexRoute = AdminResidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminResidentsRoute,
} as any)
const AdminResidentsIdRoute = AdminResidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminResidentsRoute,
} as any)
const AdminResidentsPaymentsRoute = AdminResidentsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminResidentsRoute,
} as any)
const AdminResidentsTenanciesRoute = AdminResidentsTenanciesRouteImport.update({
  id: '/tenancies',
  path: '/tenancies',
  getParentRoute: () => AdminResidentsRoute,
} as any)
const AdminWebsiteIndexRoute = AdminWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const PropertiesSlugIndexRoute = PropertiesSlugIndexRouteImport.update({
  id: '/properties/$slug/',
  path: '/properties/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteResidencesIndexRoute =
  AdminWebsiteResidencesIndexRouteImport.update({
    id: '/residences/',
    path: '/residences/',
    getParentRoute: () => AdminWebsiteRoute,
  } as any)
const AdminWebsiteResidencesIdRoute =
  AdminWebsiteResidencesIdRouteImport.update({
    id: '/residences/$id',
    path: '/residences/$id',
    getParentRoute: () => AdminWebsiteRoute,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-unlock': typeof AdminUnlockRoute
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/homes': typeof AdminHomesRouteWithChildren
  '/admin/residents': typeof AdminResidentsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/homes/availability': typeof AdminHomesAvailabilityRoute
  '/admin/homes/units': typeof AdminHomesUnitsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/admin/residents/payments': typeof AdminResidentsPaymentsRoute
  '/admin/residents/tenancies': typeof AdminResidentsTenanciesRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/homes/': typeof AdminHomesIndexRoute
  '/admin/residents/': typeof AdminResidentsIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/admin/website/residences/$id': typeof AdminWebsiteResidencesIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/admin/website/residences/': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-unlock': typeof AdminUnlockRoute
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin': typeof AdminIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/homes/availability': typeof AdminHomesAvailabilityRoute
  '/admin/homes/units': typeof AdminHomesUnitsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/admin/residents/payments': typeof AdminResidentsPaymentsRoute
  '/admin/residents/tenancies': typeof AdminResidentsTenanciesRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/homes': typeof AdminHomesIndexRoute
  '/admin/residents': typeof AdminResidentsIndexRoute
  '/admin/website': typeof AdminWebsiteIndexRoute
  '/properties/$slug': typeof PropertiesSlugIndexRoute
  '/admin/website/residences/$id': typeof AdminWebsiteResidencesIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/admin/website/residences': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-unlock': typeof AdminUnlockRoute
  '/book-viewing': typeof BookViewingRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/appointments': typeof AdminAppointmentsRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/homes': typeof AdminHomesRouteWithChildren
  '/admin/residents': typeof AdminResidentsRouteWithChildren
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/appointments/settings': typeof AdminAppointmentsSettingsRoute
  '/admin/homes/availability': typeof AdminHomesAvailabilityRoute
  '/admin/homes/units': typeof AdminHomesUnitsRoute
  '/admin/residents/$id': typeof AdminResidentsIdRoute
  '/admin/residents/payments': typeof AdminResidentsPaymentsRoute
  '/admin/residents/tenancies': typeof AdminResidentsTenanciesRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/homes/': typeof AdminHomesIndexRoute
  '/admin/residents/': typeof AdminResidentsIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/properties/$slug/': typeof PropertiesSlugIndexRoute
  '/admin/website/residences/$id': typeof AdminWebsiteResidencesIdRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/admin/website/residences/': typeof AdminWebsiteResidencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-unlock'
    | '/book-viewing'
    | '/contact'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/appointments'
    | '/admin/bookings'
    | '/admin/homes'
    | '/admin/residents'
    | '/admin/tasks'
    | '/admin/website'
    | '/admin/'
    | '/properties/'
    | '/admin/appointments/settings'
    | '/admin/homes/availability'
    | '/admin/homes/units'
    | '/admin/residents/$id'
    | '/admin/residents/payments'
    | '/admin/residents/tenancies'
    | '/admin/appointments/'
    | '/admin/homes/'
    | '/admin/residents/'
    | '/admin/website/'
    | '/properties/$slug/'
    | '/admin/website/residences/$id'
    | '/api/public/photo/$'
    | '/admin/website/residences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-unlock'
    | '/book-viewing'
    | '/contact'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/bookings'
    | '/admin/tasks'
    | '/admin'
    | '/properties'
    | '/admin/appointments/settings'
    | '/admin/homes/availability'
    | '/admin/homes/units'
    | '/admin/residents/$id'
    | '/admin/residents/payments'
    | '/admin/residents/tenancies'
    | '/admin/appointments'
    | '/admin/homes'
    | '/admin/residents'
    | '/admin/website'
    | '/properties/$slug'
    | '/admin/website/residences/$id'
    | '/api/public/photo/$'
    | '/admin/website/residences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-unlock'
    | '/book-viewing'
    | '/contact'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/admin/appointments'
    | '/admin/bookings'
    | '/admin/homes'
    | '/admin/residents'
    | '/admin/tasks'
    | '/admin/website'
    | '/admin/'
    | '/properties/'
    | '/admin/appointments/settings'
    | '/admin/homes/availability'
    | '/admin/homes/units'
    | '/admin/residents/$id'
    | '/admin/residents/payments'
    | '/admin/residents/tenancies'
    | '/admin/appointments/'
    | '/admin/homes/'
    | '/admin/residents/'
    | '/admin/website/'
    | '/properties/$slug/'
    | '/admin/website/residences/$id'
    | '/api/public/photo/$'
    | '/admin/website/residences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminUnlockRoute: typeof AdminUnlockRoute
  BookViewingRoute: typeof BookViewingRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  PropertiesSlugIndexRoute: typeof PropertiesSlugIndexRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-unlock': {
      id: '/admin-unlock'
      path: '/admin-unlock'
      fullPath: '/admin-unlock'
      preLoaderRoute: typeof AdminUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-viewing': {
      id: '/book-viewing'
      path: '/book-viewing'
      fullPath: '/book-viewing'
      preLoaderRoute: typeof BookViewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homes': {
      id: '/admin/homes'
      path: '/homes'
      fullPath: '/admin/homes'
      preLoaderRoute: typeof AdminHomesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminAppointmentsRoute
    }
    '/admin/appointments/settings': {
      id: '/admin/appointments/settings'
      path: '/settings'
      fullPath: '/admin/appointments/settings'
      preLoaderRoute: typeof AdminAppointmentsSettingsRouteImport
      parentRoute: typeof AdminAppointmentsRoute
    }
    '/admin/homes/': {
      id: '/admin/homes/'
      path: '/'
      fullPath: '/admin/homes/'
      preLoaderRoute: typeof AdminHomesIndexRouteImport
      parentRoute: typeof AdminHomesRoute
    }
    '/admin/homes/availability': {
      id: '/admin/homes/availability'
      path: '/availability'
      fullPath: '/admin/homes/availability'
      preLoaderRoute: typeof AdminHomesAvailabilityRouteImport
      parentRoute: typeof AdminHomesRoute
    }
    '/admin/homes/units': {
      id: '/admin/homes/units'
      path: '/units'
      fullPath: '/admin/homes/units'
      preLoaderRoute: typeof AdminHomesUnitsRouteImport
      parentRoute: typeof AdminHomesRoute
    }
    '/admin/residents/': {
      id: '/admin/residents/'
      path: '/'
      fullPath: '/admin/residents/'
      preLoaderRoute: typeof AdminResidentsIndexRouteImport
      parentRoute: typeof AdminResidentsRoute
    }
    '/admin/residents/$id': {
      id: '/admin/residents/$id'
      path: '/$id'
      fullPath: '/admin/residents/$id'
      preLoaderRoute: typeof AdminResidentsIdRouteImport
      parentRoute: typeof AdminResidentsRoute
    }
    '/admin/residents/payments': {
      id: '/admin/residents/payments'
      path: '/payments'
      fullPath: '/admin/residents/payments'
      preLoaderRoute: typeof AdminResidentsPaymentsRouteImport
      parentRoute: typeof AdminResidentsRoute
    }
    '/admin/residents/tenancies': {
      id: '/admin/residents/tenancies'
      path: '/tenancies'
      fullPath: '/admin/residents/tenancies'
      preLoaderRoute: typeof AdminResidentsTenanciesRouteImport
      parentRoute: typeof AdminResidentsRoute
    }
    '/admin/website/': {
      id: '/admin/website/'
      path: '/'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminWebsiteIndexRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/properties/$slug/': {
      id: '/properties/$slug/'
      path: '/properties/$slug'
      fullPath: '/properties/$slug/'
      preLoaderRoute: typeof PropertiesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/residences/': {
      id: '/admin/website/residences/'
      path: '/residences'
      fullPath: '/admin/website/residences/'
      preLoaderRoute: typeof AdminWebsiteResidencesIndexRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/residences/$id': {
      id: '/admin/website/residences/$id'
      path: '/residences/$id'
      fullPath: '/admin/website/residences/$id'
      preLoaderRoute: typeof AdminWebsiteResidencesIdRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAppointmentsRouteChildren {
  AdminAppointmentsSettingsRoute: typeof AdminAppointmentsSettingsRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
}

const AdminAppointmentsRouteChildren: AdminAppointmentsRouteChildren = {
  AdminAppointmentsSettingsRoute: AdminAppointmentsSettingsRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
}

const AdminAppointmentsRouteWithChildren =
  AdminAppointmentsRoute._addFileChildren(AdminAppointmentsRouteChildren)

interface AdminHomesRouteChildren {
  AdminHomesAvailabilityRoute: typeof AdminHomesAvailabilityRoute
  AdminHomesUnitsRoute: typeof AdminHomesUnitsRoute
  AdminHomesIndexRoute: typeof AdminHomesIndexRoute
}

const AdminHomesRouteChildren: AdminHomesRouteChildren = {
  AdminHomesAvailabilityRoute: AdminHomesAvailabilityRoute,
  AdminHomesUnitsRoute: AdminHomesUnitsRoute,
  AdminHomesIndexRoute: AdminHomesIndexRoute,
}

const AdminHomesRouteWithChildren = AdminHomesRoute._addFileChildren(
  AdminHomesRouteChildren,
)

interface AdminResidentsRouteChildren {
  AdminResidentsIdRoute: typeof AdminResidentsIdRoute
  AdminResidentsPaymentsRoute: typeof AdminResidentsPaymentsRoute
  AdminResidentsTenanciesRoute: typeof AdminResidentsTenanciesRoute
  AdminResidentsIndexRoute: typeof AdminResidentsIndexRoute
}

const AdminResidentsRouteChildren: AdminResidentsRouteChildren = {
  AdminResidentsIdRoute: AdminResidentsIdRoute,
  AdminResidentsPaymentsRoute: AdminResidentsPaymentsRoute,
  AdminResidentsTenanciesRoute: AdminResidentsTenanciesRoute,
  AdminResidentsIndexRoute: AdminResidentsIndexRoute,
}

const AdminResidentsRouteWithChildren = AdminResidentsRoute._addFileChildren(
  AdminResidentsRouteChildren,
)

interface AdminWebsiteRouteChildren {
  AdminWebsiteIndexRoute: typeof AdminWebsiteIndexRoute
  AdminWebsiteResidencesIdRoute: typeof AdminWebsiteResidencesIdRoute
  AdminWebsiteResidencesIndexRoute: typeof AdminWebsiteResidencesIndexRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteIndexRoute: AdminWebsiteIndexRoute,
  AdminWebsiteResidencesIdRoute: AdminWebsiteResidencesIdRoute,
  AdminWebsiteResidencesIndexRoute: AdminWebsiteResidencesIndexRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRouteWithChildren
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminHomesRoute: typeof AdminHomesRouteWithChildren
  AdminResidentsRoute: typeof AdminResidentsRouteWithChildren
  AdminTasksRoute: typeof AdminTasksRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRouteWithChildren,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminHomesRoute: AdminHomesRouteWithChildren,
  AdminResidentsRoute: AdminResidentsRouteWithChildren,
  AdminTasksRoute: AdminTasksRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminUnlockRoute: AdminUnlockRoute,
  BookViewingRoute: BookViewingRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  PropertiesSlugIndexRoute: PropertiesSlugIndexRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
